mos/urls.py
import settings

from django.conf.urls.defaults import *
from django.contrib import admin

from mos.admin import calendar_admin, project_admin, member_admin
from mos.cal.feeds import EventFeed


feeds = {
        'events': EventFeed,
        }

admin.autodiscover()

urlpatterns = patterns('',
   (r'^feeds/(?P<url>.*)/$',
      'django.contrib.syndication.views.feed', {'feed_dict': feeds}),

    (r'^calendar/', include('mos.cal.urls')),
    (r'^rss/', include('mos.rss.urls')),

    (r'^project/', include('mos.projects.urls')),

    (r'^$', 'mos.web.views.display_main_page'),

    (r'^site_media/(?P<path>.*)$',
     'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),

    (r'^admin/calendar/(.*)', calendar_admin.root),
    (r'^admin/projects/(.*)', project_admin.root),
    (r'^admin/members/(.*)', member_admin.root),
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),

    (r'^member/', include('mos.members.urls')),

    (r'^wiki/.*$', 'mos.web.views.wikipage'),
#    (r'^usbherelist/', include('mos.usbherelist.urls')),

    (r'^announce/$', include('mos.announce.urls')),

    (r'^cellardoor/', 'mos.web.views.display_cellardoor'),
)

mos/members/models.py
#!/usr/bin/python
# vim: set fileencoding=utf-8

import datetime

from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import Q
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import admin
from django.utils.encoding import smart_unicode



class PaymentInfo(models.Model):
    bank_collection_allowed = models.BooleanField()
    bank_collection_mode = models.ForeignKey('BankCollectionMode')
    bank_account_owner = models.CharField(max_length=200, blank=True)
    bank_account_number = models.CharField(max_length=20, blank=True)
    bank_name = models.CharField(max_length=100, blank=True)
    bank_code = models.CharField(max_length=20, blank=True)

    user = models.ForeignKey(User, unique=True)


class ContactInfo(models.Model):

    def get_image_path(self, filename):
        name, ext = filename.rsplit('.', 1)
        return 'userpics/%s.%s' %(self.user.username, ext)
    
    on_intern_list = models.BooleanField(default=True)
    intern_list_email = models.EmailField(blank=True)

    street = models.CharField(max_length=200)
    postcode = models.CharField(max_length=10)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    phone_number = models.CharField(max_length=32, blank=True)
    birthday = models.DateField(null=True, blank=True)

    wiki_name = models.CharField(max_length=50, blank=True, null=True)
    image = models.ImageField(upload_to=get_image_path, blank=True)

    user = models.ForeignKey(User, unique=True)

    last_email_ok = models.NullBooleanField(null=True)


    def get_debts(self):
        #FIXME: this is broken because it assumes that a membership period
        #       has a constant fee
        arrears = 0
        mp_list = MembershipPeriod.objects.filter(user=self.user)
        for mp in mp_list:
            fee = MembershipFee.objects.get(kind_of_membership=\
                                                mp.kind_of_membership)
            if fee.amount > 0:
                arrears += mp.get_duration_in_month()*fee.amount
        return arrears - self.get_all_payments()

    def get_debt_for_month(self, date_in_month):
        #see if the there is a membership period for the month
        mp_list = MembershipPeriod.objects.filter(user=self.user).filter(
                    Q(begin__lte=date_in_month),
                    Q(end__isnull=True) | Q(end__gte=date_in_month))

        if mp_list.count() == 0:
            return 0
        else:
           #find the membership fee for the month and kind
            #of membership and return amount
            mp = mp_list[0]
            fee = mp.kind_of_membership.membershipfee_set.filter(
                Q(start__lte=date_in_month),
                Q(end__isnull=True) | Q(end__gte=date_in_month))[0]

            return fee.amount

    def get_all_payments(self):
        payments = 0
        p_list = Payment.objects.filter(user=self.user)
        for p in p_list:
            payments += p.amount
        return payments

    def get_date_of_entry(self):
        mp = MembershipPeriod.objects.filter(user=self.user)\
            .order_by('-begin')[0]
        return mp.begin

    def get_current_membership_period(self):
        mp = MembershipPeriod.objcts.filter(user=self.user)\
            .order_by('begin')[0]
        if mp.end is None:
            return mp
        else:
            return None
        return mp.begin

    def get_wikilink(self):
        if self.wiki_name==None:
            return None
        else:
            return u'%s/Benutzer:%s' % (settings.HOS_WIKI_URL, self.wiki_name)


def get_active_members():
    return User.objects.filter(
                Q(membershipperiod__begin__lte=datetime.datetime.now()),
                Q(membershipperiod__end__isnull=True) |
                Q(membershipperiod__end__gte=datetime.datetime.now()))\
                .distinct()


class BankCollectionMode(models.Model):
    name = models.CharField(max_length=20)
    num_month = models.IntegerField()

    def __unicode__(self):
        return u"%s" % self.name


class MembershipPeriod(models.Model):
    begin = models.DateField()
    end = models.DateField(null=True, blank=True)
    user = models.ForeignKey(User)
    kind_of_membership = models.ForeignKey('KindOfMembership')

    def __unicode__(self):
        return u"%s" % self.user.username

    def get_duration_in_month(self):
        if self.end is None:
            end = datetime.date.today()
        else:
            end = self.end
        if end < self.begin:
            return 0

        begin = datetime.date(self.begin.year, self.begin.month, 1)
        end = datetime.date(end.year, end.month, 2)

        month = 0
        while begin < end:
            if begin.month == 12:
                begin = datetime.date(begin.year + 1, 1, 1)
            else:
                begin = datetime.date(begin.year, begin.month + 1, 1)
            month += 1
        return month


class MembershipFee(models.Model):
    """
    Defines the membership fee for a certain period of time.
    With this class it is possible to define different amount of
    membership fees for different periods of time and for different
    kind of members, e.g. pupils, unemployees, normal members, ...
    """

    kind_of_membership = models.ForeignKey('KindOfMembership')
    start = models.DateField()
    end = models.DateField(null=True, blank=True)
    amount = models.IntegerField()

    def __unicode__(self):
        return u"%s - %d" % (self.kind_of_membership, self.amount)


class KindOfMembership(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return u"%s" % self.name


class PaymentManager(models.Manager):
    def import_smallfile(self, f, date):
        import csv
        
        r = csv.reader(f, delimiter=";")

        for line in r:
            try:
                u = User.objects.get(first_name=smart_unicode(line[0]), last_name=smart_unicode(line[1]))
            except User.DoesNotExist:
                print line
                continue
            
            sum = line[5]

            Payment.objects.create(date=date, user=u, amount=sum, method=PaymentMethod.objects.get(name='bank collection'))


    def import_hugefile(self, f):
        import csv
        from decimal import Decimal

        r = csv.reader(f, delimiter=";")

        for line in r:
            if not line[0]:
                continue

            subject = line[2]

            if '(' in subject and ')' in subject:
                list_str = subject.split('(')[1].split(')')[0]
                if list_str == '280':
                    list = [subject.split('(')[0]]
                else:
                    list = list_str.split(',')
            else:
                list = [subject]

            sum = line[5] if line[5] else '-'+line[4] if line[4] else '0'
            
            try:
                sum = Decimal(sum) / len(list)
            except:
                print line
                continue

            for name in list:
                fragments = name.split(' ')

#                if line[0] == '2007-10-02':
#                    print name, fragments

                if fragments[0] == '':
                    fragments = fragments[1:]

                if len(fragments)==0:
                    print 'aaaaaaaaaahhh!!'
                    continue

                if fragments[0] == 'fehlgeschlagen':
                    fragments = fragments[1:]

                if 'ckzahlung' in fragments[0]:
                    fragments = fragments[1:]

                if fragments[0] == 'Ewald-Oliver':
                    fragments[0] = 'Oliver'


                if len(fragments)>1:
                    if fragments[1] in ('Sirek', 'Siereck'):
                        fragments[1] = 'Sierek'

                    if fragments[1] == 'Eckhardt':
                        fragments[1] = 'Eckardt'
                    
                    if fragments[1] == 'Grenzfurtner':
                        fragments[1] = 'Grenzfurthner'

                    if fragments[1] in ('Berg',): # Berg San, Leo Findeisen
                        fragments = fragments[1:]

                    if fragments[1] in ('Leo',):
                        fragments = [fragments[0], fragments[2]]

                    if fragments[0] == 'Schreiner':
                        fragments = [fragments[1] , fragments[0]]

                    if fragments[1] == 'Manztos':
                        fragments[1] = 'Mantzos'

                    if len(fragments)>2 and fragments[2]:
                        if fragments[2] == 'Laub':
                            fragments = fragments[1:]

                if(len(fragments)>1):
                    u = User.objects.filter(first_name__iexact=fragments[0], last_name__iexact=fragments[1])
                    if len(u)!=1:
                        print u, fragments
                    else:
                        Payment.objects.create(user=u[0], amount=sum, date=line[0], method=PaymentMethod.objects.all()[0])


                else:
                    print 'no user found for'
                    print line
        pass

class Payment(models.Model):
    amount = models.FloatField()
    comment = models.CharField(max_length=200, blank=True)
    date = models.DateField()
    method = models.ForeignKey('PaymentMethod')
    user = models.ForeignKey(User, null=True)
    original_line = models.TextField(blank=True)
    original_file = models.CharField(max_length=200, null=True)
    original_lineno = models.IntegerField(blank=True, null=True)

    objects = PaymentManager()

    def __unicode__(self):
        return u"%s" % self.user.username


class PaymentMethod(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return u"%s" % self.name


class ContactInfoInline(admin.StackedInline):
    model = ContactInfo
    max_num = 1

mos/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>{% block title %}{{ HOS_NAME }}{% endblock %}</title>
    
    <script src="/site_media/javascripts/prototype.js" type="text/javascript"></script>
    
    {% block add_css %} {% endblock add_css%}    
    
    <link href="/site_media/stylesheets/base.css" media="screen" rel="Stylesheet" type="text/css" />
    
    {% if custom_style %}
      <link href="/site_media/stylesheets/{{custom_style}}.css" media="screen" rel="Stylesheet" type="text/css" />
    {% endif %}
    
    <script src="/admin/jsi18n/" type="text/javascript"></script>    
    <script src="/admin_media/js/core.js" type="text/javascript"></script> 
    <script src="/admin_media/js/calendar.js" type="text/javascript"></script>
    <script src="/site_media/javascripts/DateTimeShortcuts.js" type="text/javascript"></script>
    
    <script src="/site_media/javascripts/ml-ajaxtools.js" type="text/javascript"></script> 
    
    <link rel="alternate" type="application/rss+xml" title="RSS" href="/feeds/events" />
 

  </head>

  <body>
    <div id="container">
      <div id="page">
	<div id="main">
	  <div id="header">
            <div id="logo">
              <a href="/" title="Hackerspace OS"><img src="/site_media/images/{% if custom_style %}{{custom_style}}.png{%else%}hackerspace_logo.png{%endif%}" width="180" height="62" alt="hackerspace os Logo" /></a>
            </div>
	    
	    {% ifequal custom_style 'ccc_linz' %}
            <div id="navbar">
	      <br />
	      <ul id="tabmenue">
		<li><a href="/wikipage/">Wiki</a></li>
		<li><a href="/member/">Members</a></li>
		<li><a href="/calendar/">Kalender</a></li>
		<li><a href="#">Kontakt</a></li>
	      </ul>
	      <div id="subtitle"> Hos ! </div>
	      {% else %}
              <ul id="header-nav">
		<li><a href="/example/" title="Wiki">Example Link</a></li>
		{% comment %}
		<li><a href="/wiki/" title="Wiki">Wiki</a></li>
		<li><a href="/wiki/Info_Folder" title="About">About</a></li>
		<li><a href="/wiki/Lage" title="Anreise">Location</a></li>
		<li><a href="/wiki/Sponsoren" title="Sponsoren">Sponsoren</a></li>
		<li><a href="/wiki/Impressum" title="Impressum">Impressum</a></li>
		{% endcomment %}
	      </ul>
	      {% endifequal %}
	      
              <div id="login">
		{% if not user.is_authenticated %} <a href="/member/login/">Login</a> {% else %} Hi <a href="/member/{{user}}">{{user}}</a>! {% if user.is_superuser %}| <a href="/admin/">Manage</a> {% endif %} |  <a href="/member/logout/">Logout</a>{% endif %}
              </div>
	    </div>
	  </div>
	  
	  <div id="content">
            {% block hos_content %}
            {% endblock %}
	  </div>
	  
	  <div id="footer"> <hr />
	    &copy; 2008 hackerspace OS - <!-- footer_stats --> 
	  </div>
	</div>
      </div>
    </div>
  </body>
</html>

mos/templates/index.html
{% extends "base.html" %}

{% block add_css %}
    <link href="/site_media/stylesheets/projects.css" media="screen" rel="Stylesheet" type="text/css" />
    <link href="/site_media/stylesheets/members.css" media="screen" rel="Stylesheet" type="text/css" />
    <link href="/site_media/stylesheets/cal.css" media="screen" rel="Stylesheet" type="text/css" />
{% endblock %}

{% block hos_content %}
  {% if not gallery and not members and introduction_text %}
	<div id="introduction_text">
	           Introduction
	</div>
  {% endif %}

  <div id="column_1">
	
     {% if gallery %}	
	<div id="gallery">
		<h1>Pics vom {{HOS_NAME}} </h1>
		<div id="hos_gallery">
			{% for image in images %}
			<div class="pic {% cycle ,last %}">
				<a href="{{image.href}}"><img src="{{ image.src }}" width="160" height="113" alt=" " /></a>
			</div>
			{% endfor %}
		</div>
	</div>
     {% endif %}

     {% if calendar %}
     	<div id="calendar">
      	    <h1><a href="/calendar/" title="Veranstaltungen">Events</a></h1>
		{% include "cal/calendar.inc" %}
        </div>
    {% endif %}

    {% if openlab %}
    	<div id="openlab">
          foo 
    	</div>
    {% endif %}
  </div>

  <div id="column_2">
	
     {% if members %}	
	<div id="members">
          <h1><a href="/member/" title="Member List">Members</a></h1>
          <div class="member_pics">
            {% for member in randommembers %}
            {% if member.contactinfo_set.all.0.get_wikilink %}<a class="member" href="{{ member.contactinfo_set.all.0.get_wikilink }}">{% endif %}<img src="{{ member.contactinfo_set.all.0.image.url }}"  width="54" height="54" alt="{{ member.username }}" />{% if member.contactinfo_set.all.0.get_wikilink %}</a>{% endif %}
            {% endfor %}
	  </div>
	</div>
     {% endif %}

     {% if  gallery and  members and introduction_text %}

	<div id="introduction_text">
	   Introduction
	</div>
     {% endif %}

     {% if projects %}
	<div id="project_list">
		<h1><a href="/project/" title="Projekte">Current Projects</a></h1>
		{% include "projects/overview.inc" %}
    	</div>
     {% endif %}

     {% if recent_changes %}
	   <div  id="recent_changes">
		{% include "rss/recentchanges.inc" %}
	  </div>
     {% endif %}
 </div>

 <script type="text/javascript">
    var calendarUpdateURL = '/calendar/ajax/list/5/';
</script>

{% endblock %}

mos/templates/wikipage.html
{% extends "base.html" %}


{% block title %}Metalab{% endblock %}

{% block hos_content %}
<style type="text/css" media="screen,projection">/*<![CDATA[*/ @import "/site_media/stylesheets/wikipage.css"; /*]]>*/</style>

		<link rel="stylesheet" type="text/css" media="print" href="/wiki/skins/common/commonPrint.css?63" />
		<link rel="stylesheet" type="text/css" media="handheld" href="/wiki/skins/monobook/handheld.css?63" />
		<!--[if lt IE 5.5000]><style type="text/css">@import "/wiki/skins/monobook/IE50Fixes.css?63";</style><![endif]-->
		<!--[if IE 5.5000]><style type="text/css">@import "/wiki/skins/monobook/IE55Fixes.css?63";</style><![endif]-->
		<!--[if IE 6]><style type="text/css">@import "/wiki/skins/monobook/IE60Fixes.css?63";</style><![endif]-->
		<!--[if IE 7]><style type="text/css">@import "/wiki/skins/monobook/IE70Fixes.css?63";</style><![endif]-->
		<!--[if lt IE 7]><script type="text/javascript" src="/wiki/skins/common/IEFixes.js?63"></script>
		<meta http-equiv="imagetoolbar" content="no" /><![endif]-->

		<script type= "text/javascript">/*<![CDATA[*/
var skin = "monobook";
var stylepath = "/wiki/skins";
var wgArticlePath = "/wiki/$1";
var wgScriptPath = "/wiki";
var wgServer = "http://localhost/mediawiki";
var wgCanonicalNamespace = "";
var wgCanonicalSpecialPageName = false;
var wgNamespaceNumber = 0;
var wgPageName = "Lage";
var wgTitle = "Lage";
var wgAction = "view";
var wgArticleId = "1687";
var wgIsArticle = true;
var wgUserName = null;
var wgUserGroups = null;
var wgUserLanguage = "de";
var wgContentLanguage = "de";
var wgBreakFrames = false;
var wgCurRevisionId = "14210";
/*]]>*/</script>


		<script type="text/javascript" src="/wiki/skins/common/wikibits.js?63"><!-- wikibits js --></script>
		<script type="text/javascript" src="/wiki/index.php?title=-&amp;action=raw&amp;gen=js"><!-- site js --></script>
		<style type="text/css">/*<![CDATA[*/
@import "/wiki/index.php?title=MediaWiki:Common.css&usemsgcache=yes&action=raw&ctype=text/css&smaxage=18000";
/*
@import "/site_media/stylesheets/monobook.css";
*/
@import "/wiki/index.php?title=-&action=raw&gen=css&maxage=18000";
/*]]>*/</style>

<form id="searchform" action="/wiki/Special:Search">
<div>
<input id="searchInput" type="text" value="adfa" accesskey="f" title="Search Wiki [alt-f]" name="search"/>
<input id="searchGoButton" class="searchButton" type="submit" title="Go to a page with this exact name if exists" value="Go" name="go"/>
<input id="mw-searchButton" class="searchButton" type="submit" title="Search the pages for this text" value="Search" name="fulltext"/>
</div>
</form>
{{ file|safe }}


{% endblock %}